### ISSUE TITLE
Find a better approach for centering blocks by default

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg-starter-theme#30]
So we don't have to manually center every block by hand. Is there a shared class we can call on?

**Comment by amdrew** [comment]
`> *` could work,  just not sure about performance (granted it's only selecting all direct children of `.entry-content`):

``` css
.entry-content > * {
    margin: 1.5em auto;
    max-width: 740px;
    padding-left: 20px;
    padding-right: 20px;
}
```
